version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-Asia/Taipei}
        CLAUDE_CODE_VERSION: latest
        GIT_DELTA_VERSION: 0.18.2
        ZSH_IN_DOCKER_VERSION: 1.2.0
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "5173:5173"

volumes:
  tubetuner_node_modules:
